import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProviderContext } from "@/context/auth";
import { Building2Icon } from "lucide-react";
import Nav from "@/components/Nav";
import { Poppins } from "next/font/google";
// import { Toaster } from "sonner";
import { Merriweather } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


const playfair = Playfair_Display({ subsets: ["latin"], weight: ["400", "700","800","900"] });
const sourceSans = Source_Sans_3({ subsets: ["latin"], weight: ["400", "700","800","900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full scroll-smooth">
      <body
        // className={`${poppins.className} relative antialiased `}
        className={`${sourceSans.className} relative antialiased `}
      >
        <AuthProviderContext>
          <Nav />
          {children}
          <Toaster richColors closeButton />
        </AuthProviderContext>
      </body>
    </html>
  );
}
// min-h-full grid grid-rows-[4rem_1fr]